void HomeScreen();
void CProgrammingFundamentals();
void BitwiseOperators();
void ArithmeticOperations();
void ArmstrongNumber();
void FibonacciSeries();
int AdditionOfEven(int num1);
int AdditionOfOdd(int num1);
bool IsMultipleOfEight(int num1);
bool IsMultipleOfSixteen(int num1);
bool IsMultipleOfThirtyTwo(int num1);
int CountOfZeroBits(int num1);
int CountOfOneBits(int num1);
bool IsOddEvenNumber(int num1);
int TurnOnBits(int num1, int noOfBits, int pos);
int TurnOffBits(int num1, int noOfBits, int pos);
int ToggleBits(int num1, int noOfBits, int pos);
int SwapBitsAtDiffPosition(int num1, int num2, int pos, int pos2, int noOfBits);
int RightMostOneBitPosition(int num1);
int MaximumNumber(int num1, int num2, int num3);
int MinimumNumber(int num1, int num2, int num3);
int LeapYear(int year);
int Palindrome(int num1);
int IsPrimeNumber(int num1);
void PrimeNumberRange(int min, int max);
void SizeOfDataTypesInC();
void Arrays();
int DifferenceAltElements(int *, int);
int RemoveIndexElement(int *, int, int);
